import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { getMe } from "@/api/api-call";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { user } = await getMe();
 
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        <ReduxProvider>
          <Header user={user} />
          {children}
          <Footer />
        </ReduxProvider>

      </body>
    </html >
  );
}
